CREATE TABLE CUR_CURRENCY_NAME_SETTING(
    ID INT NOT NULL AUTO_INCREMENT,
    CURRENCY_CODE VARCHAR(10) NOT NULL,
    `LANGUAGE` VARCHAR(5) NOT NULL,
    NAME VARCHAR(50),
    CREATE_DATE DATE,
    UPDATE_DATE DATE
);